services:
  - type: web
    name: tiktok-checkout-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8